name: Rust
version: '1.0'
main: Alpa.test.main
depend: [Citizens]
api-version: '1.20'
commands:
  그룹:
    description: 문 권한 공유를 위한 그룹 명령어입니다.
    usage: /그룹 [생성/가입] [이름]
    멤버: 그룹원 목록
    삭제: /그룹 삭제 [이름]
  보온설정:
    description: 아이템에 보온 태그를 부여합니다.
    permission: op
  방호설정:
    description: 아이템에 방호 태그를 부여합니다.
    permission: op
  bedrespawn:
    description: 클라이언트 지도 클릭 부활용 내부 명령어
    permission: bukkit.broadcast.user # 모든 유저가 사용 가능하도록 설정
  제작:
    description: 제작 메뉴를 엽니다.
  스폰설정:
    description: 현재 위치를 랜덤 리스폰 좌표 리스트에 추가합니다.
    permission: op
  레이드박스:
    description: 레이드 박스를 관리합니다.
    permission: op
  스포너설정:
    description: "새로운 필드 몹 스포너를 설정합니다."
    permission: op
  카드키:
    description: 카드키 시스템 관리 명령어
    usage: /카드키 [설정/연결]
    permission: op
  상점:
    description: 상점 GUI 열기
    permission: op
  상점등록:
    description: 지도에 상점 등록
    permission: op
  상점삭제:
    description: 지도에 상점 삭제
    permission: op